SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
SRC_DIR=$(dirname "$SCRIPT_DIR")
BASE_DIR=$(dirname "$SRC_DIR")
PROCESSED_DIR="$BASE_DIR/data_processed"
DOT_AFTER_DIR="$PROCESSED_DIR/dot_after"
DOT_BEFORE_DIR="$PROCESSED_DIR/dot_before"
DOT_CORRECT_DIR="$PROCESSED_DIR/dot_correct"
DIFF_GENERATE_DIR="$PROCESSED_DIR/diff"
DIFF_TEST_DIR="$PROCESSED_DIR/diff_test"
SRC_DIR="$BASE_DIR/src"
DIFFER_DIR="$SRC_DIR/differ"
CPP_PATH="$DIFFER_DIR/differ.cpp"
OBJ_PATH="$DIFFER_DIR/differ"
TEST_INPUT_BEFORE_PATH="$DOT_BEFORE_DIR/0.dot"
TEST_INPUT_AFTER_PATH="$DOT_AFTER_DIR/0.dot"
TEST_OUTPUT_PATH="$DIFF_TEST_DIR/diff.dot"

g++ $CPP_PATH -o $OBJ_PATH

$OBJ_PATH $TEST_INPUT_BEFORE_PATH $TEST_INPUT_AFTER_PATH $TEST_OUTPUT_PATH
